# Generated by Django 6.0.4 on 2026-05-04 10:26

import datetime
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Post date"
                    ),
                ),
                (
                    "author_name",
                    wagtail.fields.RichTextField(blank=True, max_length=100),
                ),
                ("subtitle", wagtail.fields.RichTextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("paragraph", 1),
                            ("image", 2),
                            ("blockquote", 3),
                            ("code", 4),
                            ("markdown", 4),
                            ("embed", 5),
                            ("highlight", 6),
                            ("document", 7),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "full title"},
                            ),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                            4: ("wagtail.blocks.TextBlock", (), {}),
                            5: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                            6: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic"]},
                            ),
                            7: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
